// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/16/2025, 4:02:56 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/plugins/**/*.{js,ts,mjs}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/composables/**/*.{js,ts,mjs}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/utils/**/*.{js,ts,mjs}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/jueda/Documents/git/projects-nuxtjs/recipe-app/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;